<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class KSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('indikator_K')->insert([
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P18',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P19',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P20',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P21',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P22',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P23',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P24',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P25',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P26',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P27',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P28',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P29',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P30',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P31',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P32',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P33',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
            [
                'id' => '55',
                'id_IK' => '35',
                'K' => 'P17',
                'deskripsi' => 'Peningkatan kualitas seleksi calon mahasiswa baru dan proses pembelajaran',
                'created_at' => new \DateTime,
                'updated_at' => new \DateTime,
            ],
        ]);
    }
}
