<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class TrxStatusTorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('trx_status_tor')->insert([
            [
                'id' => 1,
                'id_status' => '1',
                'id_tor' => '1',
                'create_by' => '1',
                'role_by' => 'PIC',
                'k_judul' => 'OK',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-02-23 11:02:29',
                'updated_at' => '2022-02-23 00:00:00',
            ],
            [
                'id' => 2,
                'id_status' => '2',
                'id_tor' => '1',
                'create_by' => '1',
                'role_by' => 'BPU',
                'k_judul' => 'OK',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-02-25 11:02:29',
                'updated_at' => '2022-02-25 00:00:00',
            ],
            [
                'id' => 3,
                'id_status' => '1',
                'id_tor' => '3',
                'create_by' => '1',
                'role_by' => 'PIC',
                'k_judul' => '',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 11:39:43',
                'updated_at' => '2022-04-01 07:00:00',
            ],
            [
                'id' => 4,
                'id_status' => '1',
                'id_tor' => '9',
                'create_by' => '1',
                'role_by' => 'PIC',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 22:07:39',
                'updated_at' => '2022-04-01 07:00:00',
            ],
            [
                'id' => 5,
                'id_status' => '2',
                'id_tor' => '9',
                'create_by' => '6',
                'role_by' => 'BPU',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 22:12:21',
                'updated_at' => '2022-04-01 07:00:00',
            ],
            [
                'id' => 6,
                'id_status' => '4',
                'id_tor' => '9',
                'create_by' => '5',
                'role_by' => 'WD 1',
                'k_judul' => '-',
                'k_tujuan' => 'kurang spesifik !',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 18:41:23',
                'updated_at' => '2022-04-01 07:00:00',
            ],
            [
                'id' => 7,
                'id_status' => '4',
                'id_tor' => '9',
                'create_by' => '3',
                'role_by' => 'WD 2',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 17:09:25',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id' => 8,
                'id_status' => '3',
                'id_tor' => '9',
                'create_by' => '4',
                'role_by' => 'WD 3',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => 'alamat mitra?',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 17:15:21',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id' => 9,
                'id_status' => '5',
                'id_tor' => '9',
                'create_by' => '1',
                'role_by' => 'PIC',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 21:26:02',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id' => 10,
                'id_status' => '4',
                'id_tor' => '9',
                'create_by' => '5',
                'role_by' => 'WD 1',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 22:09:14',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id' => 11,
                'id_status' => '4',
                'id_tor' => '9',
                'create_by' => '3',
                'role_by' => 'WD 2',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 22:10:19',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id' => 12,
                'id_status' => '4',
                'id_tor' => '9',
                'create_by' => '4',
                'role_by' => 'WD 3',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-01 22:10:44',
                'updated_at' => '2022-04-01 00:00:00',
            ],
            [
                'id' => 13,
                'id_status' => '2',
                'id_tor' => '3',
                'create_by' => '1',
                'role_by' => 'BPU',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-04-02 13:43:00',
                'updated_at' => '2022-04-02 00:00:00',
            ],
            [
                'id' => 14,
                'id_status' => '4',
                'id_tor' => '3',
                'create_by' => '5',
                'role_by' => 'WD 1',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-02 17:00:00',
                'updated_at' => '2022-06-02 00:00:00',
            ],
            [
                'id' => 15,
                'id_status' => '4',
                'id_tor' => '3',
                'create_by' => '3',
                'role_by' => 'WD 2',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-02 17:00:00',
                'updated_at' => '2022-06-02 00:00:00',
            ],
            [
                'id' => 16,
                'id_status' => '4',
                'id_tor' => '3',
                'create_by' => '4',
                'role_by' => 'WD 3',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-02 17:00:00',
                'updated_at' => '2022-06-02 00:00:00',
            ],
            [
                'id' => 18,
                'id_status' => '2',
                'id_tor' => '1',
                'create_by' => '6',
                'role_by' => 'BPU',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-15 08:11:57',
                'updated_at' => '2022-06-15 00:00:00',
            ],
            [
                'id' => 19,
                'id_status' => '4',
                'id_tor' => '1',
                'create_by' => '4',
                'role_by' => 'WD 3',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-15 08:12:48',
                'updated_at' => '2022-06-15 00:00:00',
            ],
            [
                'id' => 20,
                'id_status' => '1',
                'id_tor' => '10',
                'create_by' => '18',
                'role_by' => 'PIC',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-17 09:57:17',
                'updated_at' => '2022-06-17 00:00:00',
            ],
            [
                'id' => 21,
                'id_status' => '2',
                'id_tor' => '10',
                'create_by' => '6',
                'role_by' => 'BPU',
                'k_judul' => 'Sudah Baik',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-17 09:59:42',
                'updated_at' => '2022-06-17 00:00:00',
            ],
            [
                'id' => 28,
                'id_status' => '3',
                'id_tor' => '10',
                'create_by' => '5',
                'role_by' => 'WD 1',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => 'jadwal mohon diperbaiki',
                // 'k_rab' => 'anggaran mohon diperbaiki',
                'created_at' => '2022-06-17 14:44:08',
                'updated_at' => '2022-06-17 00:00:00',
            ],
            [
                'id' => 30,
                'id_status' => '5',
                'id_tor' => '10',
                'create_by' => '18',
                'role_by' => 'PIC',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-17 21:50:27',
                'updated_at' => '2022-06-17 00:00:00',
            ],
            [
                'id' => 32,
                'id_status' => '2',
                'id_tor' => '10',
                'create_by' => '6',
                'role_by' => 'BPU',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-17 22:03:09',
                'updated_at' => '2022-06-17 00:00:00',
            ],
            [
                'id' => 36,
                'id_status' => '1',
                'id_tor' => '15',
                'create_by' => '12',
                'role_by' => 'PIC',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-21 16:45:01',
                'updated_at' => '2022-06-21 00:00:00',
            ],
            [
                'id' => 37,
                'id_status' => '2',
                'id_tor' => '15',
                'create_by' => '6',
                'role_by' => 'BPU',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                // 'k_rab'=>'Tulisan lebih rapi',
                'created_at' => '2022-06-21 16:54:32',
                'updated_at' => '2022-06-21 00:00:00',
            ],
            [
                'id' => 38,
                'id_status' => '4',
                'id_tor' => '10',
                'create_by' => '1',
                'role_by' => 'WD 1',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-24 08:58:02',
                'updated_at' => '2022-06-24 00:00:00',
            ],
            [
                'id' => 39,
                'id_status' => '3',
                'id_tor' => '15',
                'create_by' => '1',
                'role_by' => 'WD 1',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => 'Mohon diperbaiki',
                'created_at' => '2022-06-28 16:52:15',
                'updated_at' => '2022-06-28 00:00:00',
            ],
            [
                'id' => 40,
                'id_status' => '1',
                'id_tor' => '14',
                'create_by' => '17',
                'role_by' => 'PIC',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-29 13:21:40',
                'updated_at' => '2022-06-29 00:00:00',
            ],
            [
                'id' => 41,
                'id_status' => '2',
                'id_tor' => '14',
                'create_by' => '6',
                'role_by' => 'BPU',
                'k_judul' => '-',
                'k_tujuan' => '-',
                'k_mekanisme' => '-',
                'k_jadwal' => '-',
                'created_at' => '2022-06-30 13:43:21',
                'updated_at' => '2022-06-30 00:00:00',
            ],
        ]);
    }
}
